#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
 
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on             \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.15           \
    window_animation_easing      ease_out_quint \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  08             \
    bottom_padding               08             \
    left_padding                 08             \
    right_padding                08             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# Border Colour
borders active_color=0xff00ff00 inactive_color=0xff494d64 width=7.0 &

# Disable specific apps
yabai -m rule --add app="^(System Settings|시스템 설정)$" manage=off
yabai -m rule --add app="^(Calculator|계산기)$" manage=off
yabai -m rule --add app="^(App Store)$" manage=off
yabai -m rule --add app="^(kakaoTalk|카카오톡)$" manage=off
yabai -m rule --add app="^(스티커)$" manage=off
yabai -m rule --add app="^(Raycast)$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^(Arc)$" subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
yabai -m rule --add app="^(무비스트 프로)$" title="(일반)" manage=off
yabai -m rule --add app="^(활성 상태 보기)$" manage=off
yabai -m rule --add app="^(League of Legends|Riot Client)$" manage=off
yabai -m rule --add app="^(Finder)$" manage=off

# Managed 
# apps=$(awk -v ORS='|' '{if($0!="") print $0}' $XDG_CONFIG_HOME/yabai/yabaimanaged)
# yabai -m rule --add app!="^${apps%?}$" manage=off
